### ISSUE TITLE
FAQ search selection in editor is broken

### ISSUE THREAD

**Issue by Krymonota** [HanashiDev/dev.hanashi.wsc.faq#163]
If you search an FAQ entry within the editor and select it, the FAQ search dialog closes, but the FAQ entry is not inserted into the editor. If you reopen the FAQ search dialog, you can see that the FAQ entry got inserted into the FAQ search dialog next to the input field:
![70C87221-4A70-4497-9772-1F496F0360F6](https://user-images.githubusercontent.com/12609161/215031176-ffdee076-42ee-44f0-ba69-ae26c5271cc8.jpeg)

WoltLab Suite 5.5.8

Not sure whether this happens only on mobile screens or always.

**Comment by Hanashi** [comment]
It's fixed in 2.1.0
