### ISSUE TITLE
Migrate to new custom icon for search result items API for WSC 6.0 compatibility

### ISSUE THREAD

**Issue by Krymonota** [HanashiDev/dev.hanashi.wsc.faq#213]
In order to ensure compatibility with WoltLab Suite Core 6.0, we need to migrate to the new custom icon for search result items API.

See:
- https://github.com/WoltLab/WCF/commit/3616f5d90ce4fb95e940a94fa2354d2fa2421de8 (old API being removed)
- https://github.com/WoltLab/WCF/pull/5461 (new API being introduced)

**Comment by Hanashi** [comment]
Migrated in 2.1.0: https://github.com/HanashiDev/dev.hanashi.wsc.faq/pull/106/commits/b493c29cedba951c23ee2ef7d22f92d5ef460420#diff-8bc7fbe1d66b17450ef31f7b22a63b53e602a95f9a664aa890d10cb389a1eaaaR102-R108
