### ISSUE TITLE
Error message(s) / links

### ISSUE THREAD

**Issue by Callixor** [HanashiDev/dev.hanashi.wsc.faq#227]
If there are error messages, the links are not displayed, but written out in HTML, see attached image.

![error_messages](https://github.com/HanashiDev/dev.hanashi.wsc.faq/assets/3521908/d2ddb18f-172e-4ed3-a371-664cfea1a16b)

Version: 2.1.1
WoltLab Suite: 6.0.10

**Comment by Hanashi** [comment]
Hi, I can reproduce this, but I have currently no solution for this, because it's triggered by a `NamedUserException`. I must rebuild this part of code.

**Comment by Hanashi** [comment]
Ref: https://www.woltlab.com/community/thread/307617-html-in-nameduserexception/

**Comment by Hanashi** [comment]
The problem occurs due to the following change: https://github.com/WoltLab/WCF/pull/5418/files

**Comment by Hanashi** [comment]
Fixed in 2.2.5
