### ISSUE TITLE
Own page for categories 

### ISSUE THREAD

**Issue by TitusKirch** [HanashiDev/dev.hanashi.wsc.faq#33]
Forum:
https://tkirch.dev/forum/thread/188-haupt-kategorie-als-eigene-seite/

**Comment by TitusKirch** [comment]
#31

**Comment by TitusKirch** [comment]
#34

**Comment by Krymonota** [comment]
I'd favour displaying the questions of the specific category and its subcategories on the page, but also allowing subcategories to have their own page.
