### ISSUE TITLE
Making categories collapsible

### ISSUE THREAD

**Issue by TitusKirch** [HanashiDev/dev.hanashi.wsc.faq#34]
Forum:
https://tkirch.dev/forum/thread/186-hauptkategorien-endanwendungen/

**Comment by TitusKirch** [comment]
@Hanashi @Krymonota If we add our own pages for categories (see #33) we won't need this anymore, or what do you think?

**Comment by Krymonota** [comment]
@TitusKirch I'm not quite sure, it probably depends on the use case. But if we introduce a separate category page, I don't see much need for collapsible categories anymore. This should cover the need of the few who have big FAQ sections on their website.

Let's keep it simple (😉) and stick to one solution. I'd prefer a seprate category page, as this seems more reasonable to me than collapsible categories that might not appeal to everyone (and would again require various ACP options to satisfy everyone's needs...)

**Comment by Hanashi** [comment]
In version 1.2.0 there will be a gallery view. So this no longer needs to be implemented. ref: https://github.com/HanashiDev/dev.hanashi.wsc.faq/pull/229/commits/a7dcfdf566222d3b10a1628f1c9d14d9ed7a695f
