### ISSUE TITLE
Prepare the release of version 2.0.0

### ISSUE THREAD

**Issue by Krymonota** [HanashiDev/dev.hanashi.wsc.faq#84]
- [x] Set package version from `2.0.0 Alpha 1` to `2.0.0`
- [x] Update package date
- [x] Check and adjust update instructions
- [x] Build release package

**Comment by Hanashi** [comment]
Don't forget to build the TypeScript files.

**Comment by Krymonota** [comment]
> Don't forget to build the TypeScript files.

Just checked - this is actually done by the `make.sh` script automatically :)
